### PR TITLE
Adding language INTERCAL

### PR DESCRIPTION
**Pull request by amandeepmittal**
This solves your issue #7

### CODE REVIEW

**Comment by angrykoala** [comment]
Hi @amandeepmittal, thanks for contributing. I see you linked to the wikipedia article, however, I think there are better resources (like the original INTERCAL) webpage to link (the url I added to the issue was just to identify the language requested.

Also, apart from the acronym, a few words about the language or its intention would be nice

**Comment by amandeepmittal** [comment]
Let me review it again, with the new link and a better description. I will get back to you.

**Comment by angrykoala** [comment]
The web is ok, I'm not sure about the description. I liked having the acronym. `compiling` I think is misspelled and I'm not sure it has "nothing in common" (although that was its intention)

What about something similar to "A parody language intended to be completely different from other languages"?

**Comment by amandeepmittal** [comment]
I think your description fits best. Can I add that? Sorry for the inconvenience.

**Comment by angrykoala** [comment]
Sure, don't worry, that's what code reviews are for.

However, if you can, check if you could improve the description, I didn't put too much though on that and probably it can be improved :)

**Comment by amandeepmittal** [comment]
I think your description is concise and fine therefore, I am updating the description.

**Pull request merged**
