### PR TITLE
Add Ark

### PR DESCRIPTION
**Pull request by spargle**
Hello!
I would like to add my passion project, Ark to this *very spicy* list.
Here are some links:
[GitHub](https://github.com/spargle/ark)
[Esolangs.org](https://esolangs.org/wiki/Ark)

### CODE REVIEW

**Comment by angrykoala** [comment]
Hi @spargle 
Thanks for your contribution, lovely language. A few things that could be nice before merging:
* Your PR looks fine, but Ark should be **before** ArnoldC (alphabetical order :smile: )
* It is up to you (what do you consider Ark's main webpage) but usually GItHub is a better source than Esolang for projects with actual compilers/interpreters (again, it is your language so it is up to you)
* I'm missing some extra docs in your project. Mainly a few examples that display more complex or interesting features of your language, small instructions to run the interpreter and a bit of an explanation on how the stack and functions work.

**Comment by spargle** [comment]
Ok. I will update the documentation on Github and Esolangs.org. As for the provided link, I will keep the Esolangs.org link because it has an interpreter link in it.

**Comment by spargle** [comment]
Alright! I have worked on the things you said and I am ready to merge whenever you are. Im doing this in between classes at school so I cant add more examples but I will when I get home.

(p.s. its my birthday)

**Comment by angrykoala** [comment]
Hi @spargle 
The description look good, and happy to keep the esolang link if you think is more accurate.

Regarding the examples and docs, I would wait until examples and better docs are ready before merge. Keep in mind that people looking at your language may have 0 context on what it is for or how to run it. Better docs will greatly improve your chances of people taking interest in your language. 

And happy birthday! (a bit late)

**Comment by spargle** [comment]
Ok. I can update the Docs this weekend. 

Thanks!

**Comment by spargle** [comment]
I have added some relatively extensive documentation to my Esolang.
[Here they are.](https://github.com/spargle/ark/blob/main/.github/docs.md)

**Comment by angrykoala** [comment]
Hi @spargle 
I've carefully reviewed all this language documentation, sadly, I think this language does not have unique enough features or design for this list, that aims to compile unique and weird languages.

PlThis list already contain several stack-based languages ([Chicken](https://esolangs.org/wiki/Chicken), [+1](https://esolangs.org/wiki/1%2B) and [tru](https://github.com/sungwoncho/tru) among others). And while Ark is clearly a distinct language, it is based on the same principles without different features.

I'll close this PR now, please feel free to answer here if I've missed something unique about the language or if new features are added in the future

Thanks again for your time and PR

**Pull request closed without merging**
