### PR TITLE
Added Almost Binary

### PR DESCRIPTION
**Pull request by wsdt**
Added the 2 future libraries too, as I'll implement them within the next few weeks.

### CODE REVIEW

**Comment by angrykoala** [comment]
@wsdt Thanks for the addition.

Everything is OK with the formatting :+1: 

A few possible improvement :smiley: 
* Try to make the description about what makes your language unique and esoteric, Ideally, people reading this list should get the basic idea on what the language is about. In this case, I would try to emphasize the idea that it is a multiplatform high-level language where you **code in binary**. I obviously don' t know a lot about your language so I may be wrong about the core idea. Likewise, I wouldn't put a lot of info on libraries or what can be used for unless it is a core idea of the language itself.

* Consider using `AlmostBinary` as the name for the entry of this list (no space). Most programming languages are named in a single word (at least in this list). Of course, you are the creator of this language and if you feel the proper name for it is using 2 words, feel free to keep it that way :)

Check the following descriptions in case that helps:
* Monicelli - Programming using Italian-like gibberish.
* Unary - Brainfuck-based language where all the commands are 0.

**Comment by wsdt** [comment]
You are right :-)
Thanks, just modified the ReadMe.

**Comment by angrykoala** [comment]
@wsdt Cool, I think the new description greatly helps to understand what the language is about. However, I feel the bit: `Code in platform-independent binary` may be hard to understand for newcomers (you code in binary vs you code using a platform-independent binary?). How about something similar to: `Platform-independent coding in binary` or `Code in binary and run in any platform`?

**Comment by wsdt** [comment]
Done 👍

**Pull request merged**
