### PR TITLE
Add C Flat

### PR DESCRIPTION
**Pull request by NicksterSand**

### CODE REVIEW

**Comment by angrykoala** [comment]
Hey @NicksterSand Great job! (I assume you are already familiar with [Fugue](https://esolangs.org/wiki/Fugue)).

I've seen the docs and check your example (I would love to listen more of those in the future :clap: ) and the whole repo is pretty cool, I've enjoyed reading the docs.

I would need a minor change to your PR before merging regarding the description "Musical language focused on expression". I understand it refers to the fact that the language tries to support music that sounds good, not only random midis. However, many people may not understand what "focused on expression" refers to. I would like the description to clearly include the things that make this language unique and interesting (I think a shorter version of the 2 points in your docs would be great)

**Comment by NicksterSand** [comment]
> Hey @NicksterSand Great job! (I assume you are already familiar with [Fugue](https://esolangs.org/wiki/Fugue)).
> 
> I've seen the docs and check your example (I would love to listen more of those in the future 👏 ) and the whole repo is pretty cool, I've enjoyed reading the docs.
> 
> I would need a minor change to your PR before merging regarding the description "Musical language focused on expression". I understand it refers to the fact that the language tries to support music that sounds good, not only random midis. However, many people may not understand what "focused on expression" refers to. I would like the description to clearly include the things that make this language unique and interesting (I think a shorter version of the 2 points in your docs would be great)

Thanks! I updated the pull request with a new description: "Musical language designed to be able to make good songs with the code discernable from audio." I tried to summarize the design philosophy as concisely as possible, but let me know if you think it still needs improvement.

**Comment by angrykoala** [comment]
@NicksterSand I think it is way better, although a bit long

What about "Musical language focused on sound rather than notation with creative freedom in mind."?

I kinda mashed up your 2 descriptions along with the key points I understood from your doc. Not sure if I correctly interpreted them, so feel free to modify so it makes more sense.

Sorry to be a bother with the description, but because the list covers ~100 languages I need them to be short and concise. plus an easy to understand  description will make it easier for people to get interested in this language

**Comment by NicksterSand** [comment]
@angrykoala That description works for me. I'll update the pull request with it.

**Pull request merged**
